imports:
    - { resource: config.yml }

doctrine:
    orm:
        metadata_cache_driver:
          type: service
          id: veonik.file_cache.default
        result_cache_driver:
          type: service
          id: veonik.file_cache.result
        query_cache_driver:
          type: service
          id: veonik.file_cache.default

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
