hwi_oauth_redirect:
  resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
  prefix:   /connect

# Authentication routes
login:
  pattern: /connect
  defaults: { _controller: OrkestraApplicationBundle:Auth:login }

login_check:
  pattern: /login/check

twitter_login:
  pattern: /login/check-twitter

github_login:
  pattern: /login/check-github

logout:
  pattern: /logout

# Bundle routes
OrkestraBundle_PasswordResetController:
  resource: "@OrkestraApplicationBundle/Controller/Auth/PasswordResetController.php"
  type:     annotation
  prefix: /manage

OrkestraBundle_UserController:
  resource: "@OrkestraApplicationBundle/Controller/UserController.php"
  type:     annotation
  prefix: /manage
  
OrkestraBundle_GroupController:
  resource: "@OrkestraApplicationBundle/Controller/GroupController.php"
  type:     annotation
  prefix: /manage

TylerSommerBlogBundle_routes:
    resource: "@TylerSommerBlogBundle/Resources/config/routing.yml"

VeonikBlogBundle_routes:
    resource: "@VeonikBlogBundle/Resources/config/routing.yml"



# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
