hwi_oauth_redirect:
  resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
  prefix:   /connect

twitter_login:
  pattern: /login/check-twitter

github_login:
  pattern: /login/check-github

# Bundle routes
OrkestraBundle_routes:
  resource: "@OrkestraApplicationBundle/Controller"
  type:     annotation
  prefix: /manage

tyler_sommer_blog:
    resource: "@TylerSommerBlogBundle/Controller/"
    type:     annotation
    prefix:   /

# Authentication routes
login:
  pattern: /manage/login
  defaults: { _controller: OrkestraApplicationBundle:Auth:login }

login_check:
  pattern: /manage/login_check


logout:
  pattern: /manage/logout



# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
