jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    role_hierarchy:
      ROLE_USER_WRITE:  ROLE_USER_READ
      ROLE_GROUP_WRITE: ROLE_GROUP_READ

      ROLE_ADMIN:       [ ROLE_USER, ROLE_USER_WRITE, ROLE_GROUP_WRITE ]
      ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    encoders:
      Orkestra\Bundle\ApplicationBundle\Entity\User: sha512

    providers:
      entity:
        entity: { class: Orkestra\Bundle\ApplicationBundle\Entity\User }

    firewalls:
        dev_and_assets:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        manage_login:
          pattern: ^/manage/login$
          security: false

        manage_area:
          provider: entity
          pattern: ^/manage
          form_login:
            login_path: /manage/login
            check_path: /manage/login_check
            username_parameter: "form[username]"
            password_parameter: "form[password]"
            default_target_path: /manage/posts

        comments_area:
          pattern:    ^/
          fp_openid: ~
          logout: true
          anonymous: true

    access_control:
      - { path: ^/login_openid$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/comment, role: IS_AUTHENTICATED_OPENID }
      - { path: ^/manage, role: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
