services:
  tylersommer.oauth.user_provider:
    class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider #TylerSommer\Bundle\BlogBundle\Security\OAuthUserProvider
    arguments: [ @doctrine.orm.entity_manager ]
